// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbxcglkzqkisfbpnvcse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZieGNnbGt6cWtpc2ZicG52Y3NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDkyNjQsImV4cCI6MjA2NDUyNTI2NH0.JUKv_ehA5PHv6_8h_aSY5FuyVu8gLS3qty3ApHQ45fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});